use rawvault;
CREATE EXTERNAL TABLE IF NOT EXISTS BEARBNW_DATATEST(   
		LVID 			VARCHAR(20) ,
		BEARBID 		INTEGER  ,    
		SCHRITTID 		INTEGER ,
	   	BEARBEITERID 		VARCHAR(20)  ,
	   	BEARBDAT 		DATE  ,
    		WIRKBEGINN 		DATE  ,
    		FEINBEGINN 		SMALLINT ,
    		WIRKENDE 		DATE  ,
	    	FEINENDE 		SMALLINT ,    
		BEARBIDSTO 		INTEGER  ,    
		BEARBDATSTO 		DATE ,    
		JOBID 			VARCHAR(30) ,    
		BEARBGRDID 		INTEGER ,    
		MELDEDAT 		DATE ,    
		WTERM 			DATE ,    
		BEARBZEIT 		VARCHAR(8) ,    
		SCHWEBEID_4AUGEN 	INTEGER ,    
		BEARBEITERID_4A 	VARCHAR(20) ,    
		PARTKEY 		SMALLINT  ,    
		BUSINESSPROCESSID 	INTEGER ,    
		KBFAUFTRAGSID 		VARCHAR(20) ,    
		BEARBKATEGORIE 		CHAR(1) ,    
		KZILISRELEVANT 		SMALLINT ,    
		BEARBRESULT 		SMALLINT ,    
		BEARBIDABG 		INTEGER  ,  
		INSERT_TST 		DATE) 
		STORED AS textfile;
LOAD DATA INPATH '/tmp/ingest/HIVE-Table-Data/BEARBNW.csv' into TABLE BEARBNW_DATATEST;

CREATE TABLE BEARBNW_ORC
STORED AS ORC
AS SELECT * from BEARBNW_DATATEST;
